#!/bin/sh

TOMCAT_FOLDER=$HOME/apache-tomcat-8.0.36

mvn clean package

$TOMCAT_FOLDER/bin/shutdown.sh
sleep 1
ps -aefl | grep tomcat | grep java | awk '{print "kill "$4}' | sh
ps -aefl | grep tomcat | grep java | awk '{print "kill -9 "$4}' | sh
sleep 1
rm -rf $TOMCAT_FOLDER/logs/*
rm -rf $TOMCAT_FOLDER/webapps/ultraRest*

cp target/ultraRest.war $TOMCAT_FOLDER/webapps/
$TOMCAT_FOLDER/bin/startup.sh

