#!/bin/sh

TOMCAT_FOLDER=/opt/tomcat/

gradle clean assemble

curl -d "" "http://localhost:8080/ultraRest/shutdown"

$TOMCAT_FOLDER/bin/shutdown.sh
sleep 1
ps -aefl | grep tomcat | grep java | awk '{print "kill "$4}' | sh
ps -aefl | grep tomcat | grep java | awk '{print "kill -9 "$4}' | sh
sleep 1
rm -rf $TOMCAT_FOLDER/logs/*
rm -rf $TOMCAT_FOLDER/webapps/ultraRest*

cp build/libs/ultraRest*.war $TOMCAT_FOLDER/webapps/ultraRest.war
$TOMCAT_FOLDER/bin/startup.sh

