#!/bin/sh
#Cleanup environment
docker stop hdfs 
docker rm -v hdfs
docker run --name hdfs -d -t -p 9000:9000 -p 50070:50070 sequenceiq/hadoop-docker
docker stop hue
docker rm -v hue
docker run -dit -p 8888:8888 --link hdfs:hdfs --name hue gethue/hue:latest bash

# Setup config files
## Seup variables
HUECONFIG=`dirname $0`"/hadoop-config/pseudo-distributed.ini"
HDFSCONFIG1=`dirname $0`"/hadoop-config/core-site.xml"
HDFSCONFIG2=`dirname $0`"/hadoop-config/hdfs-site.xml"
HDFSHOST=`docker inspect --format="{{.Config.Hostname}}" hdfs`

## Replace placeholder with actual hostname
sed "s/placeholder-container-id/$HDFSHOST/g" $HDFSCONFIG1 > /tmp/tmp.core-site.xml

## Upload config files
sleep 5
docker cp $HUECONFIG hue:/hue/desktop/conf/pseudo-distributed.ini
docker cp /tmp/tmp.core-site.xml hdfs:/usr/local/hadoop/etc/hadoop/core-site.xml
docker cp $HDFSCONFIG2 hdfs:/usr/local/hadoop/etc/hadoop/hdfs-site.xml

## Remove tempfile
#rm /tmp/tmp.core-sites.xml

# Restart DFS on HDFS
docker exec hdfs /usr/local/hadoop/sbin/stop-dfs.sh
docker exec hdfs /usr/local/hadoop/sbin/start-dfs.sh 

# Start hue
docker exec -td hue /hue/build/env/bin/hue runserver_plus 0.0.0.0:8888
